# Basic compose to start up a postgres db with adminer to alter the db
services:  
  retest: # changes server name in adminer
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data # pgdata: <- defines the volume name
    
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # a service hosted on 8080 used to manage the postgres image
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  pgdata: